name: 🚀 Deploy Laravel API to cPanel

on:
  push:
    branches:
      - main   # or master if that's your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install PHP & Composer for build
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo, mysql
          tools: composer:v2

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Clear caches before deployment
        run: |
          php artisan config:clear || true
          php artisan cache:clear || true
          php artisan route:clear || true
          php artisan view:clear || true

      # Deploy via FTP (code upload)
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/tests/**
            **/storage/logs/**

      # Run artisan migrate + optimizations over SSH
      - name: Run migrations & optimize via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home4/krysta93/inventora360/inventora360api

            # Run migrations
            php artisan migrate --force

            # Rebuild caches for production
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan event:cache

            # Optimize Laravel
            php artisan optimize
